### ISSUE TITLE
Cacatua Calendar: Year does not match Gregorian year

### ISSUE THREAD

**Issue by jvraines** [jvraines/WeirdCalendars#4]
The calendar should keep in step with the Gregorian year. There is also a problem with missing leap year method overrides.

**Comment by jvraines** [comment]
Fixed in the latest commit. Root problem was that SyncOffset needed to be 1 instead of 0. The RSS server is down at this time due to problems at the hosting service.

**Comment by jido** [comment]
I checked some dates and the feed looks right for the Cacatua calendar.
